<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <ImplicitUsings>disable</ImplicitUsings>
    <Nullable>disable</Nullable>
    <AlgoBuild>true</AlgoBuild>
    <AlgoPublish>false</AlgoPublish>
    <IncludeSource>true</IncludeSource>
    <AlgoName>FTMO_VWAP_MeanReversion_Aggressive_v1</AlgoName>
  </PropertyGroup>
  <ItemGroup>
    <Compile Remove="FTMO_VWAP_MeanReversion_v1.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="cTrader.Automate" Version="1.0.20" />
  </ItemGroup>
</Project>
